### ISSUE TITLE
Ordered CQL Expressions in Logic Highlighting HTML

### ISSUE THREAD

**Issue by lmd59** [projecttacoma/fqm-execution#238]
**Which fqm-execution feature is this request related to?**
Logic highlighting and html generation

**Describe the solution you'd like**
Re-order the CQL expressions into a more intuitive format. Currently, the CQL expressions are semi-arbitrarily ordered based on the ingestion of libraries as read from the measure bundle. Suggest explicitly ordering the CQL expressions, likely putting population definitions at the top. Function definitions could be at the bottom or in some other consistent logical order.

**Additional context**
Example of current html:
<img width="681" alt="Screen Shot 2023-05-17 at 10 29 44 AM" src="https://github.com/projecttacoma/fqm-execution/assets/2643955/91313aa3-3ff6-430b-a4fa-03ec1a73dd7d">
Population definitions are mixed in with other definitions, seemingly at random.

**Comment by mgramigna** [comment]
Just to provide another example, this is an example of what the order of expressions currently is:

![Screen Shot 2023-05-18 at 10 44 18 AM](https://github.com/projecttacoma/fqm-execution/assets/16297930/edd9db3e-5d22-4a5f-93e8-6205c5587531)

This feature would change it so that definitions used as measure populations are first, "helper definitions" are in the middle, and function definitions are at the bottom, like so:

![Screen Shot 2023-05-18 at 10 45 30 AM](https://github.com/projecttacoma/fqm-execution/assets/16297930/5479da95-59c0-41a9-9ec6-aa4a4aba3634)

**Comment by mgramigna** [comment]
We have implemented this in #242. If there is concern on how this will affect users of `fqm-execution`, we will consider changing the re-ordering to be "opt in" rather than the default behavior
