### ISSUE TITLE
Madie - Bonnie: Discrepancy between code highlighting and coverage

### ISSUE THREAD

**Issue by mcmcphillips** [projecttacoma/fqm-execution#262]
### Summary
  The included measure is displaying 100% code coverage, however the highlighting is not covering all union clauses.

#### External Tracking Ticket
  https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1511

### Expected Behavior
  Highlighting in both Madie and Bonnie would be handled the same.

### Inputs (e.g. Measure Bundle, Patient Bundle, CQL Library)
[CMS133FHIR-v0.0.007-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/12029705/CMS133FHIR-v0.0.007-FHIR4.zip)
<img width="613" alt="image" src="https://github.com/projecttacoma/fqm-execution/assets/84744653/1fa46e36-5323-46f9-81d8-8c79e429ece9">

**Comment by laclark22** [comment]
@mcmcphillips Could you please provide patient bundles for this issue? Our team has no ability of replicating this without the patients being used.

**Comment by laclark22** [comment]
@mcmcphillips just wanted to follow. up on this and see if the patient bundles were available yet?

**Comment by jkotanchik-SB** [comment]
@laclark22 Apologizes for the delay! test case bundle is attached.

[CMS133TestCaseBundles.txt](https://github.com/projecttacoma/fqm-execution/files/12129978/CMS133TestCaseBundles.txt)

**Comment by mcmcphillips** [comment]
Sorry for the lateness of my reply: 
Attached are valuesets, testcase bundles, and measure bundles.

[CMS133ValueSets.txt](https://github.com/projecttacoma/fqm-execution/files/12129994/CMS133ValueSets.txt)
[CMS133TestCaseBundles.txt](https://github.com/projecttacoma/fqm-execution/files/12129995/CMS133TestCaseBundles.txt)
[CMS133MeasureBundle.txt](https://github.com/projecttacoma/fqm-execution/files/12129996/CMS133MeasureBundle.txt)

**Comment by hossenlopp** [comment]
@mcmcphillips Thank you for the sending over the bundles, they helped us debug this issue. This issue was indeed a bug in the clause coverage percentage calculation. The percentage was not including all relevant clauses in the measure while calculating, it was only using the top level clause in each define statement. We have resolved this issue in PR #266 and accelerated our release of [v1.2.2](https://github.com/projecttacoma/fqm-execution/releases/tag/v1.2.2) to get this fix in your hands ASAP. This has been published to NPM.

There were no changes made to the visual coverage highlighting. Only the coverage percentage calculation was fixed to properly calculate based on all relevant clauses in the measure. The percentage will now correlate with what the user sees in the highlighting.

This is the highlighting that should now be expected for this measure and test case set. The percentage of clauses covered is 65.6% which is accurate due to the incomplete coverage of many of those Condition retrieves. 
<img width="898" alt="image" src="https://github.com/projecttacoma/fqm-execution/assets/11613067/8bc66da6-bc52-4f15-8c4a-8aa5172a125a">
_Reminder: Some of the `union` statements in the logic may not show visually as covered. This is due to the `union`s not always having a corresponding ELM expression clause to provide a result for them in massive multi union blocks. This is a quirk of the cql-to-elm translator and does not count against the coverage percentage calculation._

As noted in the release notes for [v1.2.2](https://github.com/projecttacoma/fqm-execution/releases/tag/v1.2.2) users will very likely see a change in coverage percentage. Most likely percentages will go down as all relevant clauses are now being included in the calculation
